version: '3'
services:
  webhook:
    build: ./webhook
    expose:
     - "8433"
    ports:
     - "8433:8433"
    volumes:
     - ./webhook:/webhook
    environment:
     - "PRODUCTION=0"
    #env_file:
    # - ./webhook/.env
