version: '3'
services:
  webhook:
    build:
      context: ./webhook
      dockerfile: Dockerfile.web
    expose:
     - "8433"
    ports:
     - "8433:8433"
    volumes:
     - ./webhook:/webhook
    environment:
     - "PRODUCTION=0"
    #env_file:
    # - ./webhook/.env
  redis:
    image: "redis:alpine"
    expose:
     - "6379"
    ports:
     - "127.0.0.1:6379:6379"
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.worker
    volumes:
     - ./worker:/worker
    depends_on:
      - redis
