FROM python:3.6-alpine
ADD . /webhook
WORKDIR /webhook

RUN pip install --no-cache-dir -q -r requirements.txt

# Run the image as a non-root user
RUN adduser -D webuser
USER webuser

CMD ["python", "webhook.py"]
