FROM python:3.6
ADD . /worker
WORKDIR /worker

ENV PYTHONUNBUFFERED 1

RUN pip install --no-cache-dir -q -r requirements.txt

# Run the image as a non-root user
RUN useradd --create-home --shell /bin/bash webuser
USER webuser

# CMD ["python", "run-worker.py"]
#CMD bash -c "alembic upgrade head && python run-worker.py"
CMD bash -c "python create_database.py && python run-worker.py"
